### ISSUE TITLE
Incompatible objects are allowed to be merged

### ISSUE THREAD

**Issue by PhilipArmstead** [voodoocreation/ts-deepmerge#26] opened 2023-05-31 12:03 UTC
Forgive me if this isn't an issue but I would expect TS to prevent me from merging two non-overlapping objects.

If I have a variable of type `Blah`

```ts
interface Blah {
  key: string;
  value: string;
}

const source: Blah = {
  key: 'abc',
  value: 'def',
};
```

and I try to merge it with something which is _not_ type `Blah`, I'd expect to see an error.

```ts
merge(source, { key: 'boop', ruh: 'roh' });
```

This is allowed, however. If I try to tell `merge` what types to expect, I get a different error:

```ts
merge<Blah>(source, { key: 'boop', ruh: 'roh' });
// TS2344: Type 'Blah' does not satisfy the constraint 'IObject[]'.
// Type 'Blah' is missing the following properties from type 'IObject[]': length, pop, push, concat, and 31 more
```

Using the normal `deepmerge` package gives me what I'd expect though.

```ts
merge<Blah>(source, { key: 'boop', ruh: 'roh' });
// TS2345: Argument of type '{ key: string; ruh: string; }' is not assignable to parameter of type 'Partial<Blah>'.
// Object literal may only specify known properties, and 'ruh' does not exist in type 'Partial<Blah>'.

**Comment by voodoocreation** [comment] 2023-06-01 00:25
Hey! You're actually using this in a bit of a different way than it was designed. When providing a type arg like that, what's happening is that it's attempting to override the bit of TS magic that's in place to be able to infer the returned object from the actual args that are provided. Because you're providing `Blah`, it's saying that it doesn't match the expected type that we have set up to safeguard against args that aren't object primitives.

The way it's been designed to work is to not provide any type arg directly, so that it can return an inferred type for the result of the deeply-merged `...args` of the function. So expecting an error when a strongly-typed object is provided first isn't quite how it's supposed to actually work, because it's all about figuring out and telling you what the final returned object actually is, based on _all_ args you provide.

If you'd like to safeguard against the returned object, you could possibly use something like `const obj: Blah = merge(...);` to ensure `obj` actually still aligns to `Blah`, or if you simply want the returned object to literally just be `Blah` without any of the inferring going on, you can use something like `const obj = merge(...) as Blah;`.

Let me know if any further context is needed though 🙏

**Closed** 2023-06-06 23:41 UTC
