### ISSUE TITLE
deepMerge is not a function

### ISSUE THREAD

**Issue by SettingDust** [voodoocreation/ts-deepmerge#22] opened 2022-11-07 15:16 UTC
The compiled js can't use
```
{
  default: [Function: merge] {
    options: { mergeArrays: true },
    withOptions: [Function (anonymous)]
  }
}

TypeError: deepMerge is not a function
```

**Comment by voodoocreation** [comment] 2022-11-07 22:12
Hey - how are you using it?

If you're using it within some CommonJS code with `require`, you may need to do this instead:
```javascript
const merge = require("ts-deepmerge").default;
```

Let me know if that helps. This package was designed for use within TS codebases with `import`/`export` syntax so it hasn't been thoroughly tested outside of that.

**Comment by voodoocreation** [comment] 2022-11-08 02:43
Can you show me how you're importing it and attempting to use it? I've never encountered this sort of issue within a TS codebase before - it generally just works like this without any issues, so it may be something to do with the way your project is being compiled?
```typescript
import merge from "ts-deepmerge";

const obj = merge({ a: true }, { b: false });

**Comment by SettingDust** [comment] 2022-11-08 02:47
I guess the [ts-swc-loader](https://github.com/kmalakoff/ts-swc-loaders) I used for test with mocha caused that. I'm trying to dig it. I don't know if it is respect my swc config.

I think it isn't a problem of code
```ts
import deepMerge from 'ts-deepmerge'
deepMerge({ title }, ...it)
```

**Comment by voodoocreation** [comment] 2022-11-08 02:50
Hmm it seems like something specific to your config/setup is impacting it somehow and causing the module to return the CommonJS module object rather than the default export from the module which would require you to import it like this instead:
```typescript
import { default as merge } from "ts-deepmerge";
```

Would be good to try and track down what's causing it to behave differently though 🤔

**Comment by SettingDust** [comment] 2022-11-08 02:51
What's compiled manually(IDK if it as same as the loader's)
```
import deepMerge from "ts-deepmerge";
deepMerge.apply(void 0, [
{
  title: title
}
].concat(_toConsumableArray(it)));
```

**Comment by SettingDust** [comment] 2022-11-08 02:54
> Does removing the `allowSyntheticDefaultImports` property from your `tsconfig.json` help at all?

Noop

> Hmm it seems like something specific to your config/setup is impacting it somehow and causing the module to return the CommonJS module object rather than the default export from the module which would require you to import it like this instead:

`import { default as deepMerge } from "ts-deepmerge";` not working

**Comment by voodoocreation** [comment] 2022-11-08 02:57
I'm not too sure what you mean there. I just know that when consumed normally this issue doesn't occur. Has been tested in a number of different contexts (eg: using the TS compiler on its own, using Webpack etc) and they all resolve as expected.

You can test it out in [this bare-bones TS template repo](https://github.com/voodoocreation/ts-package-template) of mine if you like and perhaps compare your config to that, because that one works. It's quite hard to debug your project without having access to it I'm afraid... It just seems like something within your stack is causing the module to return an object instead of the actual module.

**Comment by voodoocreation** [comment] 2022-11-08 04:04
@SettingDust did you get this working in the end? Just wondering if I can close the issue 🙏

**Comment by SettingDust** [comment] 2022-11-08 04:06
> @SettingDust did you get this working in the end? Just wondering if I can close the issue 🙏

No. I've switched from swc to esbuild and still error. Still testing

**Comment by SettingDust** [comment] 2022-11-08 04:35
Can't explain the reason. 
I guess it caused by `exports.default` which is a babel proposal(of course typescript use it too).
Maybe the project should be compiled to cjs(module.exports) and esm(export default)

**Comment by voodoocreation** [comment] 2022-11-08 04:41
Does that plugin enable it to work in your project? We have [roughly 800 public GitHub repos](https://github.com/voodoocreation/ts-deepmerge/network/dependents) depending on this package and none of them have had this issue, so it seems like it's a project configuration issue rather than an issue with the package itself.

If that plugin has allowed it to work, please let me know and I'll close this issue.

**Comment by SettingDust** [comment] 2022-11-08 05:52
It's fine with https://github.com/qnighy/node-cjs-interop. The swc plugin not working(The plugin crashed)

**Comment by krailler** [comment] 2022-12-07 10:32
I have same issue :(

**Comment by thyming** [comment] 2023-01-25 16:59
I have the same issue too. I made a reproduction that I think boils down to having "type": "module" in the consuming project's package.json. With it, typescript is happy to compile the code using this library, but the compiled code fails at runtime. Without it, everything works correctly.

**Comment by thyming** [comment] 2023-01-25 17:03
[This](https://github.com/valeriangalliat/markdown-it-anchor/issues/118) seems to be a very similar problem and they have a workaround that may work here too without complicating the build hugely.

**Comment by voodoocreation** [comment] 2023-01-25 20:44
Hmmm interesting... I'll have a look and see what I can do! 👀

**Comment by voodoocreation** [comment] 2023-01-27 01:14
I've just published [a new version](https://github.com/voodoocreation/ts-deepmerge/releases/tag/6.0.0) which now properly supports both ESM and CommonJS.

Once you update to version `6.0.0`, it should now be able to automatically use the provided ESM variant in your native ESM projects 🙏

**Closed by voodoocreation** 2023-01-27 01:14 UTC

**Comment by thyming** [comment] 2023-01-27 17:46
Glorious! Thank you!
